=== brunomichelegloria/lweb/brunomichele.gloria.PHP-MySQL/data/portafoglio.dtd
<!-- ================= ENTITÀ DI SUPPORTO ================= -->
<!ENTITY EUR "€">
<!ENTITY USD "$">
<!ENTITY GBP "£">

<!-- ================= NOTAZIONI (esempio allegati) ================= -->
<!NOTATION pdf SYSTEM "application/pdf">
<!ATTLIST documento
    tipo NOTATION (pdf) #IMPLIED
>

<!-- ================= STRUTTURA PRINCIPALE ================= -->

<!ELEMENT portafoglio (informazioni, assets, liquidita)>
<!ATTLIST portafoglio
    valuta CDATA "EUR"
>

    <!-- ===== INFORMAZIONI DEL PORTAFOGLIO ===== -->
    <!ELEMENT informazioni EMPTY>
    <!ATTLIST informazioni
        tolleranza CDATA #REQUIRED
        ultimoAggiornamento CDATA #REQUIRED
        commissione CDATA "0"
        defaultTradeStepAz CDATA "1"
        defaultTradeStepEtf CDATA "1"
        defaultTradeStepBond CDATA "1"
    >

    <!-- ===== ASSET NEGOZIABILI ===== -->
    <!ELEMENT assets (obbligazione | azione | etf | bucket)*>

        <!-- OBBLIGAZIONE -->
        <!ELEMENT obbligazione (nome?, target?, cedola?, frequenza_cedola?, scadenza?, operazioni)>
        <!ATTLIST obbligazione
            ticker CDATA #REQUIRED
            valuta CDATA "EUR"
            taxRate CDATA "0.26"
            tradeStep CDATA #IMPLIED
        >

        <!-- AZIONE -->
        <!ELEMENT azione (nome?, target?, operazioni)>
        <!ATTLIST azione
            ticker CDATA #REQUIRED
            valuta CDATA "EUR"
            taxRate CDATA "0.26"
            tradeStep CDATA #IMPLIED
        >

        <!-- ETF -->
        <!ELEMENT etf (nome?, target?, operazioni)>
        <!ATTLIST etf
            ticker CDATA #REQUIRED
            valuta CDATA "EUR"
            taxRate CDATA "0.26"
            tradeStep CDATA #IMPLIED
        >

        <!-- BUCKET (per raggruppare più asset simili) -->
        <!ELEMENT bucket (nome, target?, (azione|etf|obbligazione|bucket)*)>
        <!ATTLIST bucket
            valuta CDATA "EUR"
            tradeStep CDATA #IMPLIED
        >

            <!-- Elementi comuni -->
            <!ELEMENT nome (#PCDATA)>
            <!ELEMENT target (#PCDATA)>
            <!ELEMENT operazioni (operazione*)>

                <!ELEMENT operazione (data, quantita, prezzo)>
                <!ATTLIST operazione
                    valuta CDATA "EUR"
                >
                    <!ELEMENT data (#PCDATA)>
                    <!ELEMENT quantita (#PCDATA)>
                    <!ELEMENT prezzo (#PCDATA)>

            <!-- Solo obbligazioni -->
            <!ELEMENT cedola (#PCDATA)>
            <!ELEMENT frequenza_cedola (#PCDATA)>
            <!ELEMENT scadenza (#PCDATA)>

    <!-- ===== LIQUIDITA' ===== -->
    <!ELEMENT liquidita (totale, target?)>
    <!ATTLIST liquidita
        valuta CDATA "EUR"
    >
        <!ELEMENT totale (#PCDATA)>

=== brunomichelegloria/lweb/brunomichele.gloria.PHP-MySQL/data/portafoglio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE portafoglio SYSTEM "portafoglio.dtd">
<portafoglio valuta="€">
	<informazioni tolleranza="5" ultimoAggiornamento="2025-09-08" commissione="5"/>
	<assets>
		<bucket valuta="€">
			<nome>Tech-Giants</nome>
			<target>75</target>
			<azione ticker="AAPL" valuta="$">
				<nome>Apple</nome>
				<target>40</target>
				<operazioni>
					<operazione>
						<data>2024-05-01</data>
						<quantita>9</quantita>
						<prezzo>160</prezzo>
					</operazione>
					<operazione>
						<data>2024-06-01</data>
						<quantita>2</quantita>
						<prezzo>170</prezzo>
					</operazione>
					<operazione>
						<data>20251124-16:47:21</data>
						<quantita>5</quantita>
						<prezzo>271.960000</prezzo>
					</operazione>
					<operazione>
						<data>20251125-10:48:39</data>
						<quantita>-1</quantita>
						<prezzo>275.920000</prezzo>
					</operazione>
				</operazioni>
			</azione>
			<azione ticker="GOOGL" valuta="$">
				<nome>Google</nome>
				<target>60</target>
				<operazioni>
					<operazione>
						<data>2024-06-15</data>
						<quantita>17</quantita>
						<prezzo>120</prezzo>
					</operazione>
					<operazione>
						<data>20251124-16:47:42</data>
						<quantita>3</quantita>
						<prezzo>299.660000</prezzo>
					</operazione>
					<operazione>
						<data>20251125-10:03:24</data>
						<quantita>-4</quantita>
						<prezzo>318.580000</prezzo>
					</operazione>
				</operazioni>
			</azione>
		</bucket>
		<obbligazione ticker="IT0005532723" valuta="€" taxRate="12.5" tradeStep="1000">
			<nome>Btp Italia Mz28 Eur</nome>
			<target>25</target>
			<cedola>2.00</cedola>
			<frequenza_cedola>Semestrale</frequenza_cedola>
			<scadenza>2028-03-14</scadenza>
			<operazioni>
				<operazione>
					<data>2025-09-10</data>
					<quantita>3000</quantita>
					<prezzo>101.16062</prezzo>
				</operazione>
				<operazione>
					<data>20251120-16:47:31</data>
					<quantita>3000</quantita>
					<prezzo>102.010000</prezzo>
				</operazione>
				<operazione>
					<data>20251124-16:47:01</data>
					<quantita>-2000</quantita>
					<prezzo>0.000000</prezzo>
				</operazione>
			</operazioni>
		</obbligazione>
	</assets>
	<liquidita valuta="€">
		<totale>317.00</totale>
		<target>0</target>
	</liquidita>
</portafoglio>

=== brunomichelegloria/lweb/brunomichele.gloria.PHP-MySQL/data/goldenButterfly.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE portafoglio SYSTEM "portafoglio.dtd">
<portafoglio valuta="€">
	<informazioni tolleranza="5" ultimoAggiornamento="20251125-11:19:10" commissione="5"/>
	<assets>
		<etf ticker="EACW.MI" valuta="€">
			<nome>EACW</nome>
			<target>20</target>
			<operazioni>
				<operazione>
					<data>20251127-11:02:46</data>
					<quantita>768</quantita>
					<prezzo>20.080000</prezzo>
				</operazione>
				<operazione>
					<data>20251127-11:03:10</data>
					<quantita>158</quantita>
					<prezzo>20.870000</prezzo>
				</operazione>
				<operazione>
					<data>20251127-11:03:26</data>
					<quantita>1064</quantita>
					<prezzo>18.790000</prezzo>
				</operazione>
				<operazione>
					<data>20251127-11:03:39</data>
					<quantita>99</quantita>
					<prezzo>20.060000</prezzo>
				</operazione>
				<operazione>
					<data>20251127-11:03:56</data>
					<quantita>153</quantita>
					<prezzo>20.925000</prezzo>
				</operazione>
				<operazione>
					<data>20251127-11:04:17</data>
					<quantita>225</quantita>
					<prezzo>22.120000</prezzo>
				</operazione>
				<operazione>
					<data>20251127-11:04:54</data>
					<quantita>109</quantita>
					<prezzo>23.080000</prezzo>
				</operazione>
			</operazioni>
		</etf>
		<etf ticker="CSEMUS.MI" valuta="€">
			<nome>EU small cap</nome>
			<target>20</target>
			<operazioni/>
		</etf>
		<etf ticker="GBSE.MI" valuta="€">
			<nome>Oro hedged</nome>
			<target>20</target>
			<operazioni>
				<operazione>
					<data>20251127-10:59:40</data>
					<quantita>549</quantita>
					<prezzo>14.546000</prezzo>
				</operazione>
				<operazione>
					<data>20251127-11:00:11</data>
					<quantita>192</quantita>
					<prezzo>15.650000</prezzo>
				</operazione>
				<operazione>
					<data>20251127-11:00:27</data>
					<quantita>553</quantita>
					<prezzo>18.090000</prezzo>
				</operazione>
				<operazione>
					<data>20251127-11:00:46</data>
					<quantita>222</quantita>
					<prezzo>17.916000</prezzo>
				</operazione>
			</operazioni>
		</etf>
		<bucket valuta="€">
			<nome>LongTermBonds</nome>
			<target>20</target>
			<obbligazione ticker="IT0005534141" tradeStep="1000" valuta="€" taxRate="12.5">
				<nome>BTP 01OT53 4.50% D30</nome>
				<target>70</target>
				<operazioni>
					<operazione>
						<data>20251127-10:55:20</data>
						<quantita>26000</quantita>
						<prezzo>100.892610</prezzo>
					</operazione>
				</operazioni>
			</obbligazione>
			<obbligazione ticker="IT0004532559" tradeStep="1000" valuta="€">
				<nome>BTP-01ST40 5,00% D30</nome>
				<target>30</target>
				<operazioni>
					<operazione>
						<data>20251127-10:55:46</data>
						<quantita>9000</quantita>
						<prezzo>99.978210</prezzo>
					</operazione>
				</operazioni>
			</obbligazione>
		</bucket>
		<bucket valuta="€">
			<nome>ShortTermBonds</nome>
			<target>20</target>
			<obbligazione ticker="IT0005240830" tradeStep="1000" valuta="€">
				<nome>BTP-01GN27</nome>
				<target>17</target>
				<operazioni>
					<operazione>
						<data>20251127-10:56:17</data>
						<quantita>25000</quantita>
						<prezzo>95.808560</prezzo>
					</operazione>
				</operazioni>
			</obbligazione>
			<obbligazione ticker="IT0005521981" tradeStep="1000" valuta="€">
				<nome>BTP-01APR28 3.40%</nome>
				<target>17</target>
				<operazioni>
					<operazione>
						<data>20251127-10:56:48</data>
						<quantita>17000</quantita>
						<prezzo>99.748464</prezzo>
					</operazione>
				</operazioni>
			</obbligazione>
			<obbligazione ticker="IT0005514473" tradeStep="1000" valuta="€">
				<nome>BTP-15GE26 3.50%</nome>
				<target>17</target>
				<operazioni>
					<operazione>
						<data>20251127-10:57:15</data>
						<quantita>13000</quantita>
						<prezzo>100.964376</prezzo>
					</operazione>
				</operazioni>
			</obbligazione>
			<obbligazione ticker="IT0005428617" tradeStep="1000" valuta="€">
				<nome>CCTEU-AP26 TV EUR</nome>
				<target>17</target>
				<operazioni>
					<operazione>
						<data>20251127-10:57:38</data>
						<quantita>12000</quantita>
						<prezzo>100.606166</prezzo>
					</operazione>
				</operazioni>
			</obbligazione>
			<obbligazione ticker="IT0005547408" tradeStep="1000" valuta="€">
				<nome>BTPVAL 13GN27 SU CUM</nome>
				<target>16</target>
				<operazioni>
					<operazione>
						<data>20251127-10:58:03</data>
						<quantita>10000</quantita>
						<prezzo>100.000000</prezzo>
					</operazione>
				</operazioni>
			</obbligazione>
			<obbligazione ticker="IT0005532723" tradeStep="1000" valuta="€">
				<nome>BTPIT 14MZ28 2,00ORD</nome>
				<target>16</target>
				<operazioni>
					<operazione>
						<data>20251127-10:58:38</data>
						<quantita>10000</quantita>
						<prezzo>101.160600</prezzo>
					</operazione>
				</operazioni>
			</obbligazione>
		</bucket>
	</assets>
	<liquidita>
		<totale>2000.00</totale>
	</liquidita>
</portafoglio>
