=== brunomichelegloria/lweb/brunomichele.gloria.XML-DOM/data/portafoglio.dtd
<!-- ================= ENTITÀ DI SUPPORTO ================= -->
<!ENTITY EUR "€">
<!ENTITY USD "$">
<!ENTITY GBP "£">

<!-- ================= NOTAZIONI (esempio allegati) ================= -->
<!NOTATION pdf SYSTEM "application/pdf">
<!ATTLIST documento
    tipo NOTATION (pdf) #IMPLIED
>

<!-- ================= STRUTTURA PRINCIPALE ================= -->

<!ELEMENT portafoglio (informazioni, assets, liquidita)>
<!ATTLIST portafoglio
    valuta CDATA "EUR"
>

    <!-- ===== INFORMAZIONI DEL PORTAFOGLIO ===== -->
    <!ELEMENT informazioni EMPTY>
    <!ATTLIST informazioni
        tolleranza CDATA #REQUIRED
        ultimoAggiornamento CDATA #REQUIRED
        commissione CDATA "0"
    >

    <!-- ===== ASSET NEGOZIABILI ===== -->
    <!ELEMENT assets (obbligazione | azione | etf)*>

        <!-- OBBLIGAZIONE -->
        <!ELEMENT obbligazione (nome?, target?, operazioni, cedola?, frequenza_cedola?, scadenza?)>
        <!ATTLIST obbligazione
            ticker CDATA #REQUIRED
            valuta CDATA "EUR"
            taxRate CDATA #IMPLIED
        >

        <!-- AZIONE -->
        <!ELEMENT azione (nome?, target?, operazioni)>
        <!ATTLIST azione
            ticker CDATA #REQUIRED
            valuta CDATA "EUR"
            taxRate CDATA #IMPLIED
        >

        <!-- ETF -->
        <!ELEMENT etf (nome?, target?, operazioni)>
        <!ATTLIST etf
            ticker CDATA #REQUIRED
            valuta CDATA "EUR"
            taxRate CDATA #IMPLIED
        >

            <!-- Elementi comuni -->
            <!ELEMENT nome (#PCDATA)>
            <!ELEMENT target (#PCDATA)>
            <!ELEMENT operazioni (operazione+)>

                <!ELEMENT operazione (data, quantita, prezzo)>
                <!ATTLIST operazione
                    valuta CDATA "EUR"
                >
                    <!ELEMENT data (#PCDATA)>
                    <!ELEMENT quantita (#PCDATA)>
                    <!ELEMENT prezzo (#PCDATA)>

            <!-- Solo obbligazioni -->
            <!ELEMENT cedola (#PCDATA)>
            <!ELEMENT frequenza_cedola (#PCDATA)>
            <!ELEMENT scadenza (#PCDATA)>

    <!-- ===== LIQUIDITA' ===== -->
    <!ELEMENT liquidita (totale, target?)>
    <!ATTLIST liquidita
        valuta CDATA "EUR"
    >
        <!ELEMENT totale (#PCDATA)>

=== brunomichelegloria/lweb/brunomichele.gloria.XML-DOM/data/portafoglio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE portafoglio SYSTEM "portafoglio.dtd">
<portafoglio valuta="EUR">
  
  <informazioni tolleranza="5" ultimoAggiornamento="2025-09-08"/>

  <assets>
    <azione ticker="AAPL" valuta="USD">
      <nome>Apple</nome>
      <target>30</target>
      <operazioni>
        <operazione valuta="USD">
          <data>2024-05-01</data>
          <quantita>3</quantita>
          <prezzo>160</prezzo>
        </operazione>
        <operazione valuta="USD">
          <data>2024-06-01</data>
          <quantita>2</quantita>
          <prezzo>170</prezzo>
        </operazione>
      </operazioni>
    </azione>

    <azione ticker="GOOGL" valuta="USD">
      <nome>Google</nome>
      <target>45</target>
      <operazioni>
        <operazione valuta="USD">
          <data>2024-06-15</data>
          <quantita>5</quantita>
          <prezzo>120</prezzo>
        </operazione>
      </operazioni>
    </azione>

    <obbligazione ticker="IT0001278511" valuta="EUR">
      <nome>Btp-1nv29 5,25%</nome>
      <target>25</target>
      <operazioni>
        <operazione valuta="EUR">
          <data>2024-03-01</data>
          <quantita>10</quantita>
          <prezzo>101.45</prezzo>
        </operazione>
      </operazioni>
      <cedola>5.25</cedola>
      <frequenza_cedola>annuale</frequenza_cedola>
      <scadenza>2029-11-01</scadenza>
    </obbligazione>
  </assets>

  <liquidita valuta="EUR">
    <totale>0</totale>
    <target>0</target>
  </liquidita>

</portafoglio>

=== brunomichelegloria/lweb/brunomichele.gloria.XML-DOM/data/new/asdasd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE portafoglio SYSTEM "../portafoglio.dtd">
<portafoglio valuta="€">
	<informazioni tolleranza="5" ultimoAggiornamento="20251113-11:11:37" commissione="5"/>
	<assets>
		<azione ticker="MSFT" valuta="€">
			<nome>Microsoft</nome>
			<operazioni>
				<operazione>
					<data>20251113-11:40:45</data>
					<quantita>13</quantita>
					<prezzo>0.000000</prezzo>
				</operazione>
			</operazioni>
		</azione>
	</assets>
	<liquidita>
		<totale>300</totale>
	</liquidita>
</portafoglio>
